name: token-calculator
services:
  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "8000:8000"

  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "4200:4200"